### ISSUE TITLE
No Level System 

### ISSUE THREAD

**Issue by yalikejazz1337** [yalikejazz1337/text-based-RPG#4]
There is currently no leveling system. To add this, there should be a 'level' command, which costs 100 coins and 1000 xp to use which levels you up, giving better stats and stuff. And a level multiplier so if you're at level 2 the cost goes to 200 coins and 2000 xp.

**Comment by MoreCookies** [comment]
just like when they get the required xp amount they automatically level up and then
-it resets their current xp
-increases the xp required for the next level
-sends them like a congratulations message or something
-increases their stats
 -in order to wield better weapons/gear they have to have a certain level, which will be checked when they attempt to craft it or something idk

**Comment by yalikejazz1337** [comment]
Yes. Work on tomorrow together.
